backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Code", name: "code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Software", name: "software", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", default: 0 }
